version: '3.5'
services:
  mysql-server:
    image: mysql:8.2.0
    restart: always
    labels:
      - com.zabbix.agentd.hostname="Zabbix server"
      - com.zabbix.agentd.templates="Docker by Zabbix agent 2"
    networks:
      - zbx_net
    command:
      - mysqld
      - --character-set-server=utf8
      - --collation-server=utf8_bin
      - --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_USER=zabbix-user
      - MYSQL_DATABASE=zabbixdb
      - MYSQL_PASSWORD=MktLocal@2025!@
      - MYSQL_ROOT_PASSWORD=MktLocal@2025!@
      - ZBX_JAVAGATEWAY=zabbix-java-gateway
    volumes:
      - ./zabbix-mysql:/var/lib/mysql:rw
  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:alpine-6.4-latest
    labels:
      - com.zabbix.agentd.hostname="Zabbix server"
      - com.zabbix.agentd.templates="Docker by Zabbix agent 2"
    networks:
      - zbx_net
    restart: always
    ports:
      - 10051:10051 #zabbix server port
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./zabbix-data/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - ./zabbix-data/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./zabbix-data/export:/var/lib/zabbix/export:rw
      - ./zabbix-data/modules:/var/lib/zabbix/modules:ro
      - ./zabbix-data/enc:/var/lib/zabbix/enc:ro
      - ./zabbix-data/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./zabbix-data/mibs:/var/lib/zabbix/mibs:ro
      - ./zabbix-data/snmptraps:/var/lib/zabbix/snmptraps:rw
      - ./zabbix-logs/zabbix_server.log:/tmp/zabbix_server.log:rw
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbixdb
      - MYSQL_USER=zabbix-user
      - MYSQL_PASSWORD=MktLocal@2025!@
      - MYSQL_ROOT_PASSWORD=MktLocal@2025!@
      - ZBX_JAVAGATEWAY=zabbix-java-gateway
      - ZBX_CACHESIZE=1024M
      - ZBX_ALLOWUNSUPPORTEDDBVERSIONS=1
    depends_on:
      - mysql-server

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.4-latest
    labels:
      - com.zabbix.agentd.hostname="Zabbix server"
      - com.zabbix.agentd.templates="Docker by Zabbix agent 2"
    networks:
      - zbx_net
    ports:
      - 8087:8080
      - 8443:8443
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./zabbix-nginx/nginx:/etc/ssl/nginx:ro
      - ./zabbix-nginx/modules/:/usr/share/zabbix/modules/:ro
    environment:
      - ZBX_SERVER_HOST=zabbix-server-mysql
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbixdb
      - MYSQL_USER=zabbix-user
      - MYSQL_PASSWORD=MktLocal@2025!@
      - MYSQL_ROOT_PASSWORD=MktLocal@2025!@
    depends_on:
      - mysql-server
      - zabbix-server-mysql
  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:alpine-6.4-latest
    labels:
      - com.zabbix.agentd.hostname="Zabbix server"
      - com.zabbix.agentd.templates="Docker by Zabbix agent 2"
    restart: always
    networks:
      - zbx_net
    ports:
      - 10052:10052
networks:
  zbx_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.64.0/24
